/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines SpinEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SpinEnum
    {
        /// <summary>
        /// Enum GRAPEFRUIT for value: GRAPEFRUIT
        /// </summary>
        [EnumMember(Value = "GRAPEFRUIT")]
        GRAPEFRUIT = 1,

        /// <summary>
        /// Enum LEMON for value: LEMON
        /// </summary>
        [EnumMember(Value = "LEMON")]
        LEMON = 2,

        /// <summary>
        /// Enum LIME for value: LIME
        /// </summary>
        [EnumMember(Value = "LIME")]
        LIME = 3,

        /// <summary>
        /// Enum ORANGE for value: ORANGE
        /// </summary>
        [EnumMember(Value = "ORANGE")]
        ORANGE = 4
    }

}
