/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SlotApiController : ControllerBase
    {
        static readonly int SpinEnumValuesLength = Enum.GetValues(typeof(SpinEnum)).Length;
        
        /// <summary>
        /// Spin the slot machine
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpPost]
        [Route("/spin")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(SpinResult))]
        public virtual IActionResult Spin()
        {
            // Utilize as much CPU as we can for the next 5 seconds (for testing)
            var start = DateTime.Now;
            while ((DateTime.Now - start).TotalSeconds < 5) { }
            
            return new ObjectResult(new SpinResult
            {
                Spin1 = (SpinEnum)Random.Shared.Next(1, SpinEnumValuesLength),
                Spin2 = (SpinEnum)Random.Shared.Next(1, SpinEnumValuesLength),
                Spin3 = (SpinEnum)Random.Shared.Next(1, SpinEnumValuesLength),
            });
        }
    }
}
