/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SlotApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SlotApiTests : IDisposable
    {
        private SlotApi instance;

        public SlotApiTests()
        {
            instance = new SlotApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SlotApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SlotApi
            //Assert.IsType<SlotApi>(instance);
        }

        /// <summary>
        /// Test Spin
        /// </summary>
        [Test]
        public void SpinTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Spin();
            //Assert.IsType<SpinResult>(response);
        }
    }
}
