/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SpinEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpinEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpinEnum
        //private SpinEnum instance;

        public SpinEnumTests()
        {
            // TODO uncomment below to create an instance of SpinEnum
            //instance = new SpinEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpinEnum
        /// </summary>
        [Test]
        public void SpinEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpinEnum
            //Assert.IsType<SpinEnum>(instance);
        }

    }
}
