/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SpinResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpinResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpinResult
        //private SpinResult instance;

        public SpinResultTests()
        {
            // TODO uncomment below to create an instance of SpinResult
            //instance = new SpinResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpinResult
        /// </summary>
        [Test]
        public void SpinResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpinResult
            //Assert.IsType<SpinResult>(instance);
        }

        /// <summary>
        /// Test the property 'Spin1'
        /// </summary>
        [Test]
        public void Spin1Test()
        {
            // TODO unit test for the property 'Spin1'
        }
        /// <summary>
        /// Test the property 'Spin2'
        /// </summary>
        [Test]
        public void Spin2Test()
        {
            // TODO unit test for the property 'Spin2'
        }
        /// <summary>
        /// Test the property 'Spin3'
        /// </summary>
        [Test]
        public void Spin3Test()
        {
            // TODO unit test for the property 'Spin3'
        }
    }
}
