/*
 * Title
 *
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// The three spin results from a spin
    /// </summary>
    [DataContract]
    public partial class SpinResult : IEquatable<SpinResult>
    {
        /// <summary>
        /// Gets or Sets Spin1
        /// </summary>
        [DataMember(Name="spin1", EmitDefaultValue=true)]
        public SpinEnum Spin1 { get; set; }

        /// <summary>
        /// Gets or Sets Spin2
        /// </summary>
        [DataMember(Name="spin2", EmitDefaultValue=true)]
        public SpinEnum Spin2 { get; set; }

        /// <summary>
        /// Gets or Sets Spin3
        /// </summary>
        [DataMember(Name="spin3", EmitDefaultValue=true)]
        public SpinEnum Spin3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpinResult {\n");
            sb.Append("  Spin1: ").Append(Spin1).Append("\n");
            sb.Append("  Spin2: ").Append(Spin2).Append("\n");
            sb.Append("  Spin3: ").Append(Spin3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SpinResult)obj);
        }

        /// <summary>
        /// Returns true if SpinResult instances are equal
        /// </summary>
        /// <param name="other">Instance of SpinResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpinResult other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Spin1 == other.Spin1 ||
                    
                    Spin1.Equals(other.Spin1)
                ) && 
                (
                    Spin2 == other.Spin2 ||
                    
                    Spin2.Equals(other.Spin2)
                ) && 
                (
                    Spin3 == other.Spin3 ||
                    
                    Spin3.Equals(other.Spin3)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Spin1.GetHashCode();
                    
                    hashCode = hashCode * 59 + Spin2.GetHashCode();
                    
                    hashCode = hashCode * 59 + Spin3.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SpinResult left, SpinResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpinResult left, SpinResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
